apiVersion: v1
kind: Namespace
metadata:
  name: simple-webapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp
  labels:
    name: simple-webapp
  namespace: simple-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: simple-webapp
  template:
    metadata:
      labels:
        name: simple-webapp
    spec:
      containers:
      - name: simple-webapp
        image: awwalmustapha/simple-webapp
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-webapp
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "60d10b48-0a4a-46a5-92fe-40324ac83669"
    prometheus.io/scrape: 'true'
  labels:
    name: simple-webapp
  namespace: simple-webapp
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 80
  selector:
    name: simple-webapp



